version: '3'

services:
  MoroBooks:
    build: .
    image: moro-books:latest
    restart: unless-stopped
    container_name: moro-books-service
    environment:
      - spring.config.use-legacy-processing=true
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:sqlite:/home/sqlite/db/Books.db
      - config.moro-book-service-url=http://localhost:8081/v1/books/
    volumes:
      - ./project/deployements/db/:/home/sqlite/db
    ports:
      - 8081:8081/tcp


