server:
  port: 8081
  shutdown: GRACEFUL
spring:
  profiles:
    active: prod
  application:
    name: edi-masterdata-retrieve-service
  datasource:
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
config:
  gutendex-url: https://gutendex.com/books/
  moro-book-service-url: http://localhost:8081/v1/books/